
-- Create the ENUM type
CREATE TYPE public.account_type AS ENUM (
  'Client',
  'Employee',
  'Admin'
);

-- Optionally, set the owner of the ENUM type
ALTER TYPE public.account_type
  OWNER TO cse340jjv3;

-- Create the `classification` table
CREATE TABLE IF NOT EXISTS public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classification_name VARCHAR NOT NULL
);

-- Create the `inventory` table
CREATE TABLE IF NOT EXISTS public.inventory (
  inv_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inv_make VARCHAR NOT NULL,
  inv_color VARCHAR NOT NULL,
  inv_thumbnail VARCHAR NOT NULL,
  inv_price NUMERIC(9, 2) NOT NULL,
  classification_id INTEGER NOT NULL,
  CONSTRAINT fk_classification FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id)
    ON UPDATE CASCADE
    ON DELETE NO ACTION
);

-- Create the `account` table with ENUM type
CREATE TABLE IF NOT EXISTS public.account (
  account_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_firstname VARCHAR NOT NULL,
  account_lastname VARCHAR NOT NULL,
  account_email VARCHAR NOT NULL,
  account_password VARCHAR NOT NULL,
  account_type public.account_type NOT NULL DEFAULT 'Client'
);

-- Create the `message` table
CREATE TABLE IF NOT EXISTS public.message (
  message_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  message_to INTEGER NOT NULL,
  message_from INTEGER NOT NULL,
  message_subject VARCHAR NOT NULL,
  message_body TEXT NOT NULL,
  message_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  message_read BOOLEAN NOT NULL DEFAULT false,
  message_archived BOOLEAN NOT NULL DEFAULT false
);

-- Create relationship between columns `message_to` and `account_id`
ALTER TABLE public.message
  ADD CONSTRAINT message_to_fk FOREIGN KEY (message_to)
  REFERENCES public.account (account_id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

-- Create relationship between columns `message_from` and `account_id`
ALTER TABLE public.message
  ADD CONSTRAINT message_from_fk FOREIGN KEY (message_from)
  REFERENCES public.account (account_id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

-- Data for the `classification` table
INSERT INTO public.classification (classification_name) VALUES
  ('Premie'),
  ('0-3'),
  ('3-6'),
  ('6-9'),
  ('12'),
  ('2T'),
  ('3T'),
  ('4T'),
  ('5T');

-- Data for the `inventory` table
INSERT INTO public.inventory (
  inv_make, inv_color, inv_thumbnail, inv_price, classification_id
) VALUES 
  ('I Love U', 'White, Black, Red, Yellow, Teal', '../images/iloveu.jpg', 15.00, 1),
  ('I Love U', 'White, Black, Red, Yellow, Teal', '../images/iloveu.jpg', 15.00, 2),
  ('I Love U', 'White, Black, Red, Yellow, Teal', '../images/iloveu.jpg', 15.00, 3),
  ('I Love U', 'White, Black, Red, Yellow, Teal', '../images/iloveu.jpg', 15.00, 4),
  ('I Love U', 'White, Black, Red, Yellow, Teal', '../images/iloveu.jpg', 15.00, 5),
  ('I Like Big Bucks', 'White, Black, Red, Yellow, Teal, Camo', '../images/bucks.png', 15.00, 1),
  ('I Like Big Bucks', 'White, Black, Red, Yellow, Teal, Camo', '../images/bucks.png', 15.00, 2),
  ('I Like Big Bucks', 'White, Black, Red, Yellow, Teal, Camo', '../images/bucks.png', 15.00, 3),
  ('I Like Big Bucks', 'White, Black, Red, Yellow, Teal, Camo', '../images/bucks.png', 15.00, 4),
  ('I Like Big Bucks', 'White, Black, Red, Yellow, Teal, Camo', '../images/bucks.png', 15.00, 5),
  ('Fireman Hero', 'White, Black', '../images/firemanhero.jpg', 15.00, 1),
  ('Fireman Hero', 'White, Black', '../images/firemanhero.jpg', 15.00, 2),
  ('Fireman Hero', 'White, Black', '../images/firemanhero.jpg', 15.00, 3),
  ('Fireman Hero', 'White, Black', '../images/firemanhero.jpg', 15.00, 4),
  ('Fireman Hero', 'White, Black', '../images/firemanhero.jpg', 15.00, 5),
  ('Nurse', 'White, Black, Red, Yellow, Teal', '../images/Nurse.png', 15.00, 1),
  ('Nurse', 'White, Black, Red, Yellow, Teal', '../images/Nurse.png', 15.00, 2),
  ('Nurse', 'White, Black, Red, Yellow, Teal', '../images/Nurse.png', 15.00, 3),
  ('Nurse', 'White, Black, Red, Yellow, Teal', '../images/Nurse.png', 15.00, 4),
  ('Nurse', 'White, Black, Red, Yellow, Teal', '../images/Nurse.png', 15.00, 5),
  ('Grandpa', 'White, Black, Red, Yellow, Teal', '../images/Grandpa.png', 15.00, 1),
  ('Grandpa', 'White, Black, Red, Yellow, Teal', '../images/Grandpa.png', 15.00, 2),
  ('Grandpa', 'White, Black, Red, Yellow, Teal', '../images/Grandpa.png', 15.00, 3),
  ('Grandpa', 'White, Black, Red, Yellow, Teal', '../images/Grandpa.png', 15.00, 4),
  ('Grandpa', 'White, Black, Red, Yellow, Teal', '../images/Grandpa.png', 15.00, 5),
  ('I Love U', 'White, Black, Red, Yellow, Teal', '../images/iloveu.jpg', 20.00, 6),
  ('I Love U', 'White, Black, Red, Yellow, Teal', '../images/iloveu.jpg', 20.00, 7),
  ('I Love U', 'White, Black, Red, Yellow, Teal', '../images/iloveu.jpg', 20.00, 8),
  ('I Love U', 'White, Black, Red, Yellow, Teal', '../images/iloveu.jpg', 20.00, 9),
  ('I Like Big Bucks', 'White, Black, Red, Yellow, Teal, Camo', '../images/bucks.png', 20.00, 6),
  ('I Like Big Bucks', 'White, Black, Red, Yellow, Teal, Camo', '../images/bucks.png', 20.00, 7),
  ('I Like Big Bucks', 'White, Black, Red, Yellow, Teal, Camo', '../images/bucks.png', 20.00, 8),
  ('I Like Big Bucks', 'White, Black, Red, Yellow, Teal, Camo', '../images/bucks.png', 20.00, 9),
  ('Fireman Hero', 'White, Black', '../images/firemanhero.jpg', 20.00, 6),
  ('Fireman Hero', 'White, Black', '../images/firemanhero.jpg', 20.00, 7),
  ('Fireman Hero', 'White, Black', '../images/firemanhero.jpg', 20.00, 8),
  ('Fireman Hero', 'White, Black', '../images/firemanhero.jpg', 20.00, 9),
  ('Nurse', 'White, Black, Red, Yellow, Teal', '../images/Nurse.png', 20.00, 6),
  ('Nurse', 'White, Black, Red, Yellow, Teal', '../images/Nurse.png', 20.00, 7),
  ('Nurse', 'White, Black, Red, Yellow, Teal', '../images/Nurse.png', 20.00, 8),
  ('Nurse', 'White, Black, Red, Yellow, Teal', '../images/Nurse.png', 20.00, 9),
  ('Grandpa', 'White, Black, Red, Yellow, Teal', '../images/Grandpa.png', 20.00, 6),
  ('Grandpa', 'White, Black, Red, Yellow, Teal', '../images/Grandpa.png', 20.00, 7),
  ('Grandpa', 'White, Black, Red, Yellow, Teal', '../images/Grandpa.png', 20.00, 8),
  ('Grandpa', 'White, Black, Red, Yellow, Teal', '../images/Grandpa.png', 20.00, 9);
